package com.amazon.customskill;

import java.util.ArrayList;



import java.util.Arrays;
import java.util.List;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.IntStream;

import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.amazon.speech.json.SpeechletRequestEnvelope;
import com.amazon.speech.slu.Intent;
import com.amazon.speech.speechlet.IntentRequest;
import com.amazon.speech.speechlet.LaunchRequest;
import com.amazon.speech.speechlet.SessionEndedRequest;
import com.amazon.speech.speechlet.SessionStartedRequest;
import com.amazon.speech.speechlet.SpeechletResponse;
import com.amazon.speech.speechlet.SpeechletV2;
import com.amazon.speech.ui.PlainTextOutputSpeech;
import com.amazon.speech.ui.Reprompt;
import com.amazon.speech.ui.SsmlOutputSpeech;

public class AlexaSkillSpeechlet2 {
private void selectQuestion() {
	Random r = new Random();
	int questions = r.nextInt(15);
		String question;
		String correctAnswer;
		switch(questions){
		case 1: question = "viele auf englisch"; correctAnswer = "a lot"; break;
		case 2: question = "über, etwa, circa"; correctAnswer = "about"; break;
		case 3: question = "über, oben, obenstehend"; correctAnswer = "above"; break;
		case 4: question = "Adresse"; correctAnswer = "address"; break;
		case 5: question = "nach"; correctAnswer = "after"; break;
		case 6: question = "Nachmittag"; correctAnswer = "afternoon"; break;
		case 7: question = "wieder"; correctAnswer = "again"; break;
		case 8: question = "gegen, an"; correctAnswer = "against"; break;
		case 9: question = "Alter"; correctAnswer = "age"; break;
		case 10: question = "Luft"; correctAnswer = "air"; break;
		case 11: question = "Flughafen"; correctAnswer = "airport"; break;
		case 12: question = "alle"; correctAnswer = "all"; break;
		case 13: question = "entlang, weiter vorwärts"; correctAnswer = "along"; break;
		case 14: question = "auch, außerdem"; correctAnswer = "also"; break;
		case 15: question = "immer"; correctAnswer = "always"; break;
		case 16: question = "Amerikaner,in amerikanisch"; correctAnswer = "American"; break;
		case 17: question = "Tier"; correctAnswer = "animal"; break;
		case 18: question = "beantworten, Antwort"; correctAnswer = "answer"; break;
		case 19: question = "irgendetwas, irgendwelche"; correctAnswer = "any"; break;
		case 20: question = "jemand, jeder"; correctAnswer = "anyone"; break;
		case 21: question = "etwas"; correctAnswer = "anything"; break;
		case 22: question = "Apfel"; correctAnswer = "apple"; break;
		case 23: question = "Arm"; correctAnswer = "arm"; break;
		case 24: question = "ankommen"; correctAnswer = "arrive"; break;
		case 25: question = "fragen, bitten"; correctAnswer = "ask"; break;
		case 26: question = "in; an; bei; auf; zu; hin"; correctAnswer = "at"; break;
		case 27: question = "zu Hause"; correctAnswer = "at home"; break;
		case 28: question = "im Augenblick"; correctAnswer = "at the moment"; break;
		case 29: question = "Tante"; correctAnswer = "aunt"; break;
		case 30: question = "Osterreich"; correctAnswer = "Austria"; break;
		case 31: question = "Osterreicher, Osterreicherin"; correctAnswer = "Austrian"; break;
		case 32: question = "Herbst"; correctAnswer = "autumn"; break;
		case 33: question = "erhältlich, verfügbar"; correctAnswer = "available"; break;
		case 34: question = "Baby, Säugling"; correctAnswer = "baby"; break;
		case 35: question = "Rücken"; correctAnswer = "back"; break;
		case 36: question = "Schinkenspeck"; correctAnswer = "bacon"; break;
		case 37: question = "schlecht, schlimm"; correctAnswer = "bad"; break;
		case 38: question = "Bäcker"; correctAnswer = "baker"; break;
		case 39: question = "Banane"; correctAnswer = "banana"; break;
		case 40: question = "Bank, Ufer"; correctAnswer = "bank"; break;
		case 41: question = "Bar, Lokal, Theke"; correctAnswer = "bar"; break;
		case 42: question = "Barkeeper"; correctAnswer = "barman"; break;
		case 43: question = "Bad, Badewanne"; correctAnswer = "bath"; break;
		case 44: question = "sein"; correctAnswer = "to be"; break;
		case 45: question = "schön"; correctAnswer = "beautiful"; break;
		case 46: question = "weil"; correctAnswer = "because"; break;
		case 47: question = "Bett"; correctAnswer = "bed"; break;
		case 48: question = "Schlafzimmer"; correctAnswer = "bedroom"; break;
		case 49: question = "Bier"; correctAnswer = "beer"; break;
		case 50: question = "bevor, zuvor"; correctAnswer = "before"; break;
		case 51: question = "anfangen, beginnen"; correctAnswer = "begin"; break;
		case 52: question = "Anfang"; correctAnswer = "beginning"; break;
		case 53: question = "hinter, hinten"; correctAnswer = "behind"; break;
		case 54: question = "zwischen"; correctAnswer = "between"; break;
		case 55: question = "unter, unten"; correctAnswer = "below"; break;
		case 56: question = "Fahrrad"; correctAnswer = "bicyle"; break;
		case 57: question = "groß"; correctAnswer = "big"; break;
		case 58: question = "Fahrrad"; correctAnswer = "bike"; break;
		case 59: question = "Vogel"; correctAnswer = "bird"; break;
		case 60: question = "Geburtstag"; correctAnswer = "birthday"; break;
		case 61: question = "schwarz"; correctAnswer = "black"; break;
		case 62: question = "Blut"; correctAnswer = "blood"; break;
		case 63: question = "Boot, Schiff"; correctAnswer = "boat"; break;
		case 64: question = "Körper"; correctAnswer = "body"; break;
		case 65: question = "Buch"; correctAnswer = "book"; break;
		case 66: question = "Flasche"; correctAnswer = "bottle"; break;
		case 67: question = "Kästchen"; correctAnswer = "box"; break;
		case 68: question = "Junge"; correctAnswer = "boy"; break;
		case 69: question = "Freund"; correctAnswer = "boyfriend"; break;
		case 70: question = "Freund, Freundin"; correctAnswer = "friend"; break;
		case 71: question = "Freundin"; correctAnswer = "girlfriend"; break;
		case 72: question = "Ast"; correctAnswer = "branch"; break;
		case 73: question = "Brot"; correctAnswer = "bread"; break;
		case 74: question = "Frühstück"; correctAnswer = "breakfast"; break;
		case 75: question = "bringen, mitbringen, holen"; correctAnswer = "bring"; break;
		case 76: question = "Großbritannien"; correctAnswer = "Great Britain"; break;
		case 77: question = "britisch"; correctAnswer = "british"; break;
		case 78: question = "Bruder"; correctAnswer = "brother"; break;
		case 79: question = "braun"; correctAnswer = "brown"; break;
		case 80: question = "bauen"; correctAnswer = "build"; break;
		case 81: question = "Bus"; correctAnswer = "bus"; break;
		case 82: question = "aber, sondern, als"; correctAnswer = "but"; break;
		case 83: question = "Fleischer, Fleischerin"; correctAnswer = "butcher"; break;
		case 84: question = "kaufen"; correctAnswer = "buy"; break;
		case 85: question = "bis, durch, per, von"; correctAnswer = "by"; break;
		case 86: question = "Kuchen, Torte, Gebäckstück"; correctAnswer = "cake"; break;
		case 87: question = "Fotoapparat, Kamera"; correctAnswer = "camera"; break;
		case 88: question = "Zelten"; correctAnswer = "camping"; break;
		case 89: question = "können"; correctAnswer = "can"; break;
		case 90: question = "nicht können"; correctAnswer = "cannot"; break;
		case 91: question = "Kanal"; correctAnswer = "canal"; break;
		case 92: question = "Auto"; correctAnswer = "car"; break;
		case 93: question = "Katze"; correctAnswer = "cat"; break;
		case 94: question = "zentral, mittlere, mittlerer, mittleres"; correctAnswer = "central"; break;
		case 95: question = "Stuhl"; correctAnswer = "chair"; break;
		case 96: question = "sich ändern, verändern"; correctAnswer = "change"; break;
		case 97: question = "Scheck"; correctAnswer = "check"; break;
		case 98: question = "überprüfen, prüfen"; correctAnswer = "check"; break;
		case 99: question = "Käse"; correctAnswer = "cheese"; break;
		case 100: question = "Kind"; correctAnswer = "child"; break;
		case 101: question = "Pommes Frites"; correctAnswer = "chips"; break;
		case 102: question = "Schokolade, Praline"; correctAnswer = "chocolate"; break;
		case 103: question = "wählen, aussuchen"; correctAnswer = "choose"; break;
		case 104: question = "Kirche"; correctAnswer = "church"; break;
		case 105: question = "Zigarette"; correctAnswer = "cigarette"; break;
		case 106: question = "Kino"; correctAnswer = "cinema"; break;
		case 107: question = "Kreis"; correctAnswer = "circle"; break;
		case 108: question = "Stadt"; correctAnswer = "city || town"; break;
		case 109: question = "Klasse, Schulklasse, Unterricht"; correctAnswer = "class"; break;
		case 110: question = "Klassenraum, Klassenzimmer"; correctAnswer = "class room"; break;
		case 111: question = "sauber"; correctAnswer = "clean"; break;
		case 112: question = "klettern"; correctAnswer = "climb"; break;
		case 113: question = "Uhr"; correctAnswer = "clock"; break;
		case 114: question = "Uhr"; correctAnswer = "watch"; break;
		case 115: question = "zumachen"; correctAnswer = "close"; break;
		case 116: question = "geschlossen"; correctAnswer = "closed"; break;
		case 117: question = "Kleider, Kleidung"; correctAnswer = "clothes"; break;
		case 118: question = "Mantel"; correctAnswer = "coat"; break;
		case 119: question = "Kaffee"; correctAnswer = "coffee"; break;
		case 120: question = "kalt"; correctAnswer = "cold"; break;
		case 121: question = "Fachschule, Berufsfachschule"; correctAnswer = "college"; break;
		case 122: question = "Fachhochschule, Universität"; correctAnswer = "college"; break;
		case 123: question = "Farbe"; correctAnswer = "colour"; break;
		case 124: question = "kommen"; correctAnswer = "come"; break;
		case 125: question = "Computer"; correctAnswer = "computer"; break;
		case 126: question = "Konzert"; correctAnswer = "concert"; break;
		case 127: question = "kochen, Koch, Köchin"; correctAnswer = "cook"; break;
		case 128: question = "Ecke"; correctAnswer = "corner"; break;
		case 129: question = "kosten"; correctAnswer = "cost"; break;
		case 130: question = "Land"; correctAnswer = "country"; break;
		case 131: question = "Cousin, Cousine"; correctAnswer = "cousin"; break;
		case 132: question = "Kuh"; correctAnswer = "cow"; break;
		case 133: question = "Sahne, Creme"; correctAnswer = "cream"; break;
		case 134: question = "Kreuz"; correctAnswer = "cross"; break;
		case 135: question = "Tasse"; correctAnswer = "cup"; break;
		case 136: question = "Schrank"; correctAnswer = "cupboard"; break;
		case 137: question = "Papa, Vater"; correctAnswer = "dad"; break;
		case 138: question = "tanzen"; correctAnswer = "dance"; break;
		case 139: question = "gefährlich"; correctAnswer = "dangerous || dangerously"; break;
		case 140: question = "Datum"; correctAnswer = "date"; break;
		case 141: question = "Tochter"; correctAnswer = "daughter"; break;
		case 142: question = "Tag"; correctAnswer = "day"; break;
		case 143: question = "tot"; correctAnswer = "dead"; break;
		case 144: question = ""; correctAnswer = ""; break;
		case 145: question = "lieber, liebe"; correctAnswer = "dear"; break;
		case 146: question = "beschreiben"; correctAnswer = "describe"; break;
		case 147: question = "sterben"; correctAnswer = "die"; break;
		case 148: question = "schwer, schwierig"; correctAnswer = "difficult"; break;
		case 149: question = "Abendessen"; correctAnswer = "dinner"; break;
		case 150: question = "Diskothek"; correctAnswer = "disco"; break;
		case 151: question = "tun, machen"; correctAnswer = "do"; break;
		case 152: question = "Arzt, Ärztin"; correctAnswer = "doctor"; break;
		case 153: question = "Hund"; correctAnswer = "dog"; break;
		case 154: question = "Tür"; correctAnswer = "door"; break;
		case 155: question = "Doppel"; correctAnswer = "double"; break;
		case 156: question = "nach unten, hinunter, herunter, unten"; correctAnswer = "down"; break;
		case 157: question = "Kleid"; correctAnswer = "dress"; break;
		case 158: question = "trinken, Getränk"; correctAnswer = "drink"; break;
		case 159: question = "fahren"; correctAnswer = "drive"; break;
		case 160: question = "Fahrerin, Fahrer"; correctAnswer = "driver"; break;
		case 161: question = "jede, jeder, jedes"; correctAnswer = "each || every || everyone"; break;
		case 162: question = "Ohr"; correctAnswer = "ear"; break;
		case 163: question = "früh"; correctAnswer = "early"; break;
		case 164: question = "Osten"; correctAnswer = "east"; break;
		case 165: question = "einfach, leicht"; correctAnswer = "easy || easily"; break;
		case 166: question = "essen, fressen"; correctAnswer = "eat"; break;
		case 167: question = "Ei"; correctAnswer = "disco"; break;
		case 168: question = "leer"; correctAnswer = "empty"; break;
		case 169: question = "England"; correctAnswer = "England"; break;
		case 170: question = "Englisch"; correctAnswer = "English"; break;
		case 171: question = "genießen"; correctAnswer = "enjoy"; break;
		case 172: question = "Europa"; correctAnswer = "Europe"; break;
		case 173: question = "Europäerin, europäisch"; correctAnswer = "European"; break;
		case 174: question = "Abend"; correctAnswer = "evening"; break;
		case 175: question = "alles"; correctAnswer = "everything"; break;
		case 176: question = "überall, überallhin"; correctAnswer = "everywhere"; break;
		case 177: question = "Beispiel"; correctAnswer = "example"; break;
		case 178: question = "entschuldigen"; correctAnswer = "excuse"; break;
		case 179: question = "Übung"; correctAnswer = "exercise"; break;
		case 180: question = "erwarten"; correctAnswer = "expect"; break;
		case 181: question = "expensive"; correctAnswer = "teuer"; break;
		case 182: question = "Auge"; correctAnswer = "eye"; break;
		case 183: question = "Familie"; correctAnswer = "family"; break;
		case 184: question = "Familienname"; correctAnswer = "family name"; break;
		case 185: question = "weit"; correctAnswer = "far"; break;
		case 186: question = "Bauernhof"; correctAnswer = "farm"; break;
		case 187: question = "Bäuerin, Bauer"; correctAnswer = "farmer"; break;
		case 188: question = "schnell"; correctAnswer = "fast"; break;
		case 189: question = "Vater"; correctAnswer = "father"; break;
		case 190: question = "Film"; correctAnswer = "film || movie"; break;
		case 191: question = "finden"; correctAnswer = "find"; break;
		case 192: question = "Finger"; correctAnswer = "finger"; break;
		case 193: question = "beenden, abschließen"; correctAnswer = "finish"; break;
		case 194: question = "ertse, erster, erstes"; correctAnswer = "first"; break;
		case 195: question = "Vorname"; correctAnswer = "first name"; break;
		case 196: question = "Fisch"; correctAnswer = "fish"; break;
		case 197: question = "fit"; correctAnswer = "fit"; break;
		case 198: question = "flach"; correctAnswer = "flat"; break;
		case 199: question = "Wohnung"; correctAnswer = "flat"; break;
		case 200: question = "Etage, Fußboden"; correctAnswer = "floor"; break;
		case 201: question = "Fiege"; correctAnswer = "fly"; break;
		case 202: question = "folgen"; correctAnswer = "follow"; break;
		case 203: question = "Essen, Lebensmittel"; correctAnswer = "food"; break;
		case 204: question = "Fuß"; correctAnswer = "foot"; break;
		case 205: question = "Fußball"; correctAnswer = "football"; break;
		case 206: question = "für"; correctAnswer = "for"; break;
		case 207: question = "Gabel"; correctAnswer = "fork"; break;
		case 208: question = "Formular, bilden"; correctAnswer = "form"; break;
		case 209: question = "Frankreich"; correctAnswer = "France"; break;
		case 210: question = "kostenlos, frei"; correctAnswer = "free"; break;
		case 211: question = "Französisch"; correctAnswer = "French"; break;
		case 212: question = "Freundin, Freund"; correctAnswer = "friend"; break;
		case 213: question = "von, aus"; correctAnswer = "from"; break;
		case 214: question = "Vorderseite, Vorderteil"; correctAnswer = "front"; break;
		case 215: question = "Obst, Frucht"; correctAnswer = "fruit"; break;
		case 216: question = "voll"; correctAnswer = "full"; break;
		case 217: question = "komisch"; correctAnswer = "weird || funny"; break;
		case 218: question = "Spiel"; correctAnswer = "game"; break;
		case 219: question = "Garten"; correctAnswer = "garden"; break;
		case 220: question = "deutsch"; correctAnswer = "German"; break;
		case 221: question = "Deutschland"; correctAnswer = "Germany"; break;
		case 222: question = "bekommen, werden"; correctAnswer = "get"; break;
		case 223: question = "Mädchen"; correctAnswer = "girl"; break;
		case 224: question = "geben, schenken"; correctAnswer = "give"; break;
		case 225: question = "go"; correctAnswer = "gehen || fahren"; break;
		case 226: question = "good"; correctAnswer = "gut"; break;
		case 227: question = "auf Wiedersehen"; correctAnswer = "goodbye"; break;
		case 228: question = "leben, wohnen"; correctAnswer = "live"; break;
		case 229: question = "Großvater"; correctAnswer = "granddad || grandfather"; break;
		case 230: question = "Enkelin"; correctAnswer = "granddaugther"; break;
		case 231: question = "Großmutter"; correctAnswer = "grandma || grandmother"; break;
		case 232: question = "Großeltern"; correctAnswer = "grandparents"; break;
		case 233: question = "toll, großartig"; correctAnswer = "great"; break;
		case 234: question = "grün"; correctAnswer = "green"; break;
		case 235: question = "Gruppe"; correctAnswer = "group"; break;
		case 236: question = "wachsen"; correctAnswer = "grow"; break;
		case 237: question = "Gitarre"; correctAnswer = "guitar"; break;
		case 238: question = "Haar"; correctAnswer = "hair"; break;
		case 239: question = "Frisörin, Frisör"; correctAnswer = "hairdresser"; break;
		case 240: question = "Hälfte"; correctAnswer = "half"; break;
		case 241: question = "Hand"; correctAnswer = "hand"; break;
		case 242: question = "glücklich, zufrieden"; correctAnswer = "happy"; break;
		case 243: question = "haben"; correctAnswer = "have"; break;
		case 244: question = "Kopf"; correctAnswer = "head"; break;
		case 245: question = "Gesundheit"; correctAnswer = "health"; break;
		case 246: question = "gesund"; correctAnswer = "healthy"; break;
		case 247: question = "hören"; correctAnswer = "hear || listen"; break;
		case 248: question = "hallo"; correctAnswer = "hello"; break;
		case 249: question = "Hilfe, helfen"; correctAnswer = "help"; break;
		case 250: question = "hier"; correctAnswer = "here"; break;
		case 251: question = "hoch"; correctAnswer = "high"; break;
		case 252: question = "Ferien, Urlaub, Feiertag"; correctAnswer = "holiday"; break;
		case 253: question = "Zuhause"; correctAnswer = "home"; break;
		case 254: question = "Hausaufgaben"; correctAnswer = "homework"; break;
		case 255: question = "Pferd"; correctAnswer = "horse"; break;
		case 256: question = "Krankenhaus"; correctAnswer = "hospital"; break;
		case 257: question = "heiß, warm"; correctAnswer = "warm || hot"; break;
		case 258: question = "Hotel"; correctAnswer = "hotel"; break;
		case 259: question = "Stunde"; correctAnswer = "hour"; break;
		case 260: question = "Haus"; correctAnswer = "house"; break;
		case 261: question = "wie"; correctAnswer = "how"; break;
		case 262: question = "wie viel"; correctAnswer = "how much"; break;
		case 263: question = "wie viele"; correctAnswer = "how many"; break;
		case 264: question = "hungrig"; correctAnswer = "hungry"; break;
		case 265: question = "Ehemann"; correctAnswer = "husband"; break;
		case 266: question = "Eis"; correctAnswer = "ice"; break;
		case 267: question = "Idee, Gedanke, Vorstellung"; correctAnswer = "idea"; break;
		case 268: question = "wenn, falls"; correctAnswer = "if"; break;
		case 269: question = "krank"; correctAnswer = "ill"; break;
		case 270: question = "wichtig"; correctAnswer = "important"; break;
		case 271: question = "in, auf, hinein"; correctAnswer = "in"; break;
		case 272: question = "in etwas hinein"; correctAnswer = "into || into something"; break;
		case 273: question = "Italien"; correctAnswer = "Italy"; break;
		case 274: question = "Jacke, Jackett"; correctAnswer = "jacket"; break;
		case 275: question = "Jeans"; correctAnswer = "jeans"; break;
		case 276: question = "Arbeit, Aufgabe"; correctAnswer = "work || job"; break;
		case 277: question = "Witz, Scherz"; correctAnswer = "joke"; break;
		case 278: question = "nur, gerade"; correctAnswer = "just"; break;
		case 279: question = "Schlüssel"; correctAnswer = "key"; break;
		case 280: question = "töten, umbringen"; correctAnswer = "kill"; break;
		case 281: question = "Kilometer"; correctAnswer = "kilometre"; break;
		case 282: question = "König"; correctAnswer = "king"; break;
		case 283: question = "Küche"; correctAnswer = "kitchen"; break;
		case 284: question = "Messer"; correctAnswer = "knife"; break;
		case 285: question = "kennen, wissen"; correctAnswer = "know"; break;
		case 286: question = "Aufkleber, Etikett"; correctAnswer = "label"; break;
		case 287: question = "Lampe"; correctAnswer = "lamp"; break;
		case 288: question = "Sprache"; correctAnswer = "language"; break;
		case 289: question = "groß"; correctAnswer = "large"; break;
		case 290: question = "letzte, letzter, letztes"; correctAnswer = "last"; break;
		case 291: question = "lernen"; correctAnswer = "learn"; break;
		case 292: question = "abreisen, weggehen, verlassen"; correctAnswer = "leave"; break;
		case 293: question = "links"; correctAnswer = "left"; break;
		case 294: question = "Bein"; correctAnswer = "leg"; break;
		case 295: question = "Schulstunde"; correctAnswer = "lesson"; break;
		case 296: question = "lassen"; correctAnswer = "let"; break;
		case 297: question = "Buchstabe, Brief"; correctAnswer = "letter"; break;
		case 298: question = "Leben"; correctAnswer = "life"; break;
		case 299: question = "Aufzug"; correctAnswer = "lift"; break;
		case 300: question = "wie"; correctAnswer = "like"; break;
		case 301: question = "mögen, gern haben"; correctAnswer = "like"; break;
		case 302: question = "Linie, Zeile"; correctAnswer = "line"; break;
		case 303: question = "Liste, auflisten"; correctAnswer = "list"; break;
		case 304: question = "zuhören"; correctAnswer = "listen"; break;
		case 305: question = "hören, sich anhören"; correctAnswer = "listen to"; break;
		case 306: question = "klein, wenig"; correctAnswer = "little"; break;
		case 307: question = "Teil"; correctAnswer = "part"; break;
		case 308: question = "lang"; correctAnswer = "long"; break;
		case 309: question = "sehen, schauen"; correctAnswer = "look"; break;
		case 310: question = "sich anschauen"; correctAnswer = "look at"; break;
		case 311: question = "suchen"; correctAnswer = "look for || search"; break;
		case 312: question = "verlieren"; correctAnswer = "lose"; break;
		case 313: question = "Menge"; correctAnswer = "lot || amount"; break;
		case 314: question = "lieben"; correctAnswer = "love"; break;
		case 315: question = "niedrig"; correctAnswer = "low"; break;
		case 316: question = "glücklich"; correctAnswer = "lucky || happy"; break;
		case 317: question = "Mittagessen"; correctAnswer = "lunch"; break;
		case 318: question = "Zeitschrift, Magazin"; correctAnswer = "magazine"; break;
		case 319: question = "tun, machen"; correctAnswer = "make"; break;
		case 320: question = "Mann"; correctAnswer = "man"; break;
		case 321: question = "Leiterin, Leiter"; correctAnswer = "manager"; break;
		case 322: question = "viele"; correctAnswer = "many"; break;
		case 323: question = "Streichholz"; correctAnswer = "match"; break;
		case 324: question = "dürfen, können"; correctAnswer = "may"; break;
		case 325: question = "vielleicht"; correctAnswer = "maybe"; break;
		case 326: question = "Fleisch"; correctAnswer = "meat"; break;
		case 327: question = "treffen, begegnen"; correctAnswer = "meet"; break;
		case 328: question = "Meile"; correctAnswer = "mile"; break;
		case 329: question = "Milch"; correctAnswer = "milk"; break;
		case 330: question = "Million"; correctAnswer = "million"; break;
		case 331: question = "Minute"; correctAnswer = "minute"; break;
		case 332: question = "verpassen"; correctAnswer = "miss"; break;
		case 333: question = "Mama"; correctAnswer = "mother || mom"; break;
		case 334: question = "Moment"; correctAnswer = "moment"; break;
		case 335: question = "Geld"; correctAnswer = "money"; break;
		case 336: question = "Monat"; correctAnswer = "month"; break;
		case 337: question = "Moped, Mofa"; correctAnswer = "moped"; break;
		case 338: question = "Morgen"; correctAnswer = "morning"; break;
		case 339: question = "Mund"; correctAnswer = "mouth"; break;
		case 340: question = "bewegen"; correctAnswer = "move"; break;
		case 341: question = "viel"; correctAnswer = "much"; break;
		case 342: question = "Musik"; correctAnswer = "music"; break;
		case 343: question = "müssen"; correctAnswer = "must"; break;
		case 344: question = "Name"; correctAnswer = "name"; break;
		case 345: question = "beinhae, fast"; correctAnswer = "nearly"; break;
		case 346: question = "Hals"; correctAnswer = "neck"; break;
		case 347: question = "nie, niemals"; correctAnswer = "never"; break;
		case 348: question = "neu"; correctAnswer = "new"; break;
		case 349: question = "Zeitung"; correctAnswer = "newspaper"; break;
		case 350: question = "nächste, nächster, nächstes"; correctAnswer = "next"; break;
		case 351: question = "schön, nett"; correctAnswer = "nice"; break;
		case 352: question = "Nacht"; correctAnswer = "night"; break;
		case 353: question = "nein"; correctAnswer = "no"; break;
		case 354: question = "niemand"; correctAnswer = "nobody || noone"; break;
		case 355: question = "keine, keiner, keines"; correctAnswer = "none"; break;
		case 356: question = "Unsinn"; correctAnswer = "nonsense"; break;
		case 357: question = "normal, üblich"; correctAnswer = "normal"; break;
		case 358: question = "Norden"; correctAnswer = "north"; break;
		case 359: question = "Nase"; correctAnswer = "nose"; break;
		case 360: question = "nicht"; correctAnswer = "not"; break;
		case 361: question = "nichts"; correctAnswer = "nothing"; break;
		case 362: question = "bemerken"; correctAnswer = "notice || recognize"; break;
		case 363: question = "nun, jetzt"; correctAnswer = "now"; break;
		case 364: question = "Nummer, Zahl"; correctAnswer = "number"; break;
		case 365: question = "ein Uhr"; correctAnswer = "one o´clock"; break;
		case 366: question = "ungerade"; correctAnswer = "odd"; break;
		case 367: question = "von"; correctAnswer = "of"; break;
		case 368: question = "Angebot, anbieten"; correctAnswer = "offer"; break;
		case 369: question = "Büro"; correctAnswer = "office"; break;
		case 370: question = "oft, häufig"; correctAnswer = "often"; break;
		case 371: question = "alt"; correctAnswer = "old"; break;
		case 372: question = "auf, an"; correctAnswer = "on"; break;
		case 373: question = "offen, aufmachen"; correctAnswer = "open"; break;
		case 374: question = "Meinung"; correctAnswer = "opinion"; break;
		case 375: question = "oder"; correctAnswer = "or"; break;
		case 376: question = "andere, anderer, anderes"; correctAnswer = "other"; break;
		case 377: question = "draußen, hinaus, heraus"; correctAnswer = "out || outside"; break;
		case 378: question = "über"; correctAnswer = "over"; break;
		case 379: question = "Seite"; correctAnswer = "page"; break;
		case 380: question = "Paar"; correctAnswer = "pair"; break;
		case 381: question = "Palast"; correctAnswer = "palace"; break;
		case 382: question = "Papier"; correctAnswer = "paper"; break;
		case 383: question = "Elternteil"; correctAnswer = "parent"; break;
		case 384: question = "Park"; correctAnswer = "park"; break;
		case 385: question = "parken"; correctAnswer = "park"; break;
		case 386: question = "Anblick, Sehvermögen"; correctAnswer = "sight"; break;
		case 387: question = "singen"; correctAnswer = "sing"; break;
		case 388: question = "Partnerin, Partner"; correctAnswer = "partner"; break;
		case 389: question = "Party, Fest"; correctAnswer = "party"; break;
		case 390: question = "bezahlen"; correctAnswer = "pay"; break;
		case 391: question = "Erbse"; correctAnswer = "pea"; break;
		case 392: question = "Kugelschreiber"; correctAnswer = "pen"; break;
		case 393: question = "Leute, Menschen"; correctAnswer = "people"; break;
		case 394: question = "Mensch, Person"; correctAnswer = "person"; break;
		case 395: question = "Telefon, anrufen"; correctAnswer = "phone"; break;
		case 396: question = "Foto"; correctAnswer = "photo"; break;
		case 397: question = "Redewendung"; correctAnswer = "phrase"; break;
		case 398: question = "Klavier"; correctAnswer = "piano"; break;
		case 399: question = "Bild"; correctAnswer = "picture"; break;
		case 400: question = "Stück, Teil"; correctAnswer = "piece"; break;
		case 401: question = "Platz, Ort"; correctAnswer = "place"; break;
		case 402: question = "Plan, planen, vorhaben"; correctAnswer = "plan"; break;
		case 403: question = "Flugzeug"; correctAnswer = "airplane || plane"; break;
		case 404: question = "Teller"; correctAnswer = "plate"; break;
		case 405: question = "spielen"; correctAnswer = "play"; break;
		case 406: question = "gefallen"; correctAnswer = "please"; break;
		case 407: question = "bitte"; correctAnswer = "please"; break;
		case 408: question = "froh, erfreut"; correctAnswer = "pleased || happy"; break;
		case 409: question = "Polizei"; correctAnswer = "police"; break;
		case 410: question = "Polizist"; correctAnswer = "policeman"; break;
		case 411: question = "Polizistin"; correctAnswer = "policewoman"; break;
		case 412: question = "Popmusik"; correctAnswer = "pop music"; break;
		case 413: question = "Post"; correctAnswer = "post"; break;
		case 414: question = "Plakat"; correctAnswer = "poster"; break;
		case 415: question = "Briefträger"; correctAnswer = "postman"; break;
		case 416: question = "Briefträgerin"; correctAnswer = "post woman"; break;
		case 417: question = "Kartoffel"; correctAnswer = "potato"; break;
		case 418: question = "Pfund, Sterling"; correctAnswer = "pound"; break;
		case 419: question = "Geschenk"; correctAnswer = "present"; break;
		case 420: question = "hübsch"; correctAnswer = "pretty"; break;
		case 421: question = "Problem"; correctAnswer = "problem"; break;
		case 422: question = "Wirtshaus, Kneipe"; correctAnswer = "pub"; break;
		case 423: question = "Pullover"; correctAnswer = "pullover || sweatshirt"; break;
		case 424: question = "setzen, stellen, legen"; correctAnswer = "put"; break;
		case 425: question = "Viertel"; correctAnswer = "quarter"; break;
		case 426: question = "Königin"; correctAnswer = "queen"; break;
		case 427: question = "Frage"; correctAnswer = "question"; break;
		case 428: question = "schnell"; correctAnswer = "quick || quickly"; break;
		case 429: question = "ziemlich"; correctAnswer = "quite"; break;
		case 430: question = "Radio, Rundfunk"; correctAnswer = "radio"; break;
		case 431: question = "Regen, regnen"; correctAnswer = "rain"; break;
		case 432: question = "lesen"; correctAnswer = "read"; break;
		case 433: question = "echt, wirklich"; correctAnswer = "real"; break;
		case 434: question = "reason"; correctAnswer = "Grund"; break;
		case 435: question = "rot"; correctAnswer = "red"; break;
		case 436: question = "sich erinnern, daran denken"; correctAnswer = "remember"; break;
		case 437: question = "Reis"; correctAnswer = "rice"; break;
		case 438: question = "reiten"; correctAnswer = "ride"; break;
		case 439: question = "rechts, richtig"; correctAnswer = "right"; break;
		case 440: question = "Recht haben"; correctAnswer = "be right"; break;
		case 441: question = "Straße"; correctAnswer = "road"; break;
		case 442: question = "Zimmer, Raum, Paltz"; correctAnswer = "room"; break;
		case 443: question = "rund, um herum"; correctAnswer = "round"; break;
		case 444: question = "laufen, rennen"; correctAnswer = "run"; break;
		case 445: question = "traurig"; correctAnswer = "sad"; break;
		case 446: question = "sicher"; correctAnswer = "safe || safely"; break;
		case 447: question = "Salat"; correctAnswer = "salad"; break;
		case 448: question = "Verkauf, Ausverkauf"; correctAnswer = "sale"; break;
		case 449: question = "gleich, dasselbe"; correctAnswer = "same"; break;
		case 450: question = "Belegtes Brot"; correctAnswer = "sandwich"; break;
		case 451: question = "sagen"; correctAnswer = "say"; break;
		case 452: question = "Schule"; correctAnswer = "school"; break;
		case 453: question = "Meer"; correctAnswer = "sea"; break;
		case 454: question = "zweite, zweiter, zweites"; correctAnswer = "second"; break;
		case 455: question = "Sekunde"; correctAnswer = "second"; break;
		case 456: question = "sehen"; correctAnswer = "see"; break;
		case 457: question = "verkaufen"; correctAnswer = "sell"; break;
		case 458: question = "senden, schicken"; correctAnswer = "send"; break;
		case 459: question = "Schiff"; correctAnswer = "ship"; break;
		case 460: question = "Laden, Geschäft"; correctAnswer = "shop"; break;
		case 461: question = "Einkaufen"; correctAnswer = "shopping"; break;
		case 462: question = "kurz, klein"; correctAnswer = "short"; break;
		case 463: question = "zeigen"; correctAnswer = "show"; break;
		case 464: question = "Dusche"; correctAnswer = "shower"; break;
		case 465: question = "Seite, Rand"; correctAnswer = "side"; break;
		case 466: question = "Straßenbahn"; correctAnswer = "tram"; break;
		case 467: question = "Verkehrsmittel"; correctAnswer = "transport"; break;
		case 468: question = "Schwester"; correctAnswer = "sister"; break;
		case 469: question = "sitzen"; correctAnswer = "sit"; break;
		case 470: question = "schlafen"; correctAnswer = "sleep"; break;
		case 471: question = "langsam"; correctAnswer = "slow || slowly"; break;
		case 472: question = "klein"; correctAnswer = "small"; break;
		case 473: question = "rauchen"; correctAnswer = "smoke"; break;
		case 474: question = "Schnee"; correctAnswer = "snow"; break;
		case 475: question = "also"; correctAnswer = "so"; break;
		case 476: question = "Sofa"; correctAnswer = "sofa"; break;
		case 477: question = "leise, weich"; correctAnswer = "soft"; break;
		case 478: question = "einige, etwas"; correctAnswer = "some"; break;
		case 479: question = "jemand"; correctAnswer = "somebody || someone"; break;
		case 480: question = "etwas"; correctAnswer = "something"; break;
		case 481: question = "manchmal"; correctAnswer = "sometimes"; break;
		case 482: question = "Sohn"; correctAnswer = "son"; break;
		case 483: question = "bald"; correctAnswer = "soon"; break;
		case 484: question = "traurig"; correctAnswer = "sorry"; break;
		case 485: question = "Süden"; correctAnswer = "south"; break;
		case 486: question = "sprechen, reden"; correctAnswer = "speak"; break;
		case 487: question = "Quadrat"; correctAnswer = "square"; break;
		case 488: question = "stehen"; correctAnswer = "stand"; break;
		case 489: question = "beginnen"; correctAnswer = "start"; break;
		case 490: question = "Bahnhof"; correctAnswer = "station || train station"; break;
		case 491: question = "bleiben, übernachten"; correctAnswer = "stay"; break;
		case 492: question = "immernoch"; correctAnswer = "still"; break;
		case 493: question = "anhalten, halten"; correctAnswer = "stop"; break;
		case 494: question = "Erzählung, Gschichte"; correctAnswer = "stroy"; break;
		case 495: question = "Straße"; correctAnswer = "street || road"; break;
		case 496: question = "stark"; correctAnswer = "strong"; break;
		case 497: question = "Studentin, Student"; correctAnswer = "student"; break;
		case 498: question = "Zucker"; correctAnswer = "sugar"; break;
		case 499: question = "Koffer"; correctAnswer = "suitcase"; break;
		case 500: question = "Sommer"; correctAnswer = "summer"; break;
		case 501: question = "Sonne"; correctAnswer = "sun"; break;
		case 502: question = "Supermarkt"; correctAnswer = "supermarket"; break;
		case 503: question = "sicher, freilich"; correctAnswer = "sure"; break;
		case 504: question = "Nachname"; correctAnswer = "surname"; break;
		case 505: question = "Umfrage"; correctAnswer = "survey"; break;
		case 506: question = "Süßigkeiten"; correctAnswer = "sweets"; break;
		case 507: question = "schwimmen"; correctAnswer = "swim"; break;
		case 508: question = "Schweiz"; correctAnswer = "Switzerland"; break;
		case 509: question = "Tisch, Tabelle"; correctAnswer = "table"; break;
		case 510: question = "nehmen, bringen"; correctAnswer = "take"; break;
		case 511: question = "sprechen über"; correctAnswer = "talk about"; break;
		case 512: question = "Tee"; correctAnswer = "tea"; break;
		case 513: question = "Lererin, Lehrer"; correctAnswer = "teacher"; break;
		case 514: question = "Telefon"; correctAnswer = "telephone || phone"; break;
		case 515: question = "Fernseher, Fernsehen"; correctAnswer = "television"; break;
		case 516: question = "sagen, erzählen"; correctAnswer = "tell"; break;
		case 517: question = "Text"; correctAnswer = "text"; break;
		case 518: question = "mehr als"; correctAnswer = "more than"; break;
		case 519: question = "danken, sich bedanken"; correctAnswer = "thank"; break;
		case 520: question = "danke"; correctAnswer = "thank you || thanks"; break;
		case 521: question = "dass"; correctAnswer = "that"; break;
		case 522: question = "dann"; correctAnswer = "then"; break;
		case 523: question = "dort, dorthin"; correctAnswer = "there"; break;
		case 524: question = "es gibt"; correctAnswer = "there are || there is"; break;
		case 525: question = "diese"; correctAnswer = "these"; break;
		case 526: question = "Sache, Ding"; correctAnswer = "thing"; break;
		case 527: question = "denken, glauben"; correctAnswer = "think || believe"; break;
		case 528: question = "diese, dieser, dies"; correctAnswer = "this"; break;
		case 529: question = "jene"; correctAnswer = "those"; break;
		case 530: question = "durch, hindurch"; correctAnswer = "through"; break;
		case 531: question = "Fahrkarte"; correctAnswer = "ticket"; break;
		case 532: question = "Zeit, Uhrzeit, Mal"; correctAnswer = "time"; break;
		case 533: question = "Fahrplan, Stundenplan"; correctAnswer = "timetable"; break;
		case 534: question = "müde"; correctAnswer = "tired"; break;
		case 535: question = "zu, nach, in, um zu"; correctAnswer = "to"; break;
		case 536: question = "heute"; correctAnswer = "today"; break;
		case 537: question = "Zehe"; correctAnswer = "toe"; break;
		case 538: question = "zusammen"; correctAnswer = "together"; break;
		case 539: question = "morgen"; correctAnswer = "tomorrow"; break;
		case 540: question = "heute Abend"; correctAnswer = "tonight"; break;
		case 541: question = "auch"; correctAnswer = "too || also"; break;
		case 542: question = "Stadt"; correctAnswer = "town || city"; break;
		case 543: question = "Straßenverkehr"; correctAnswer = "traffic"; break;
		case 544: question = "Zug"; correctAnswer = "train"; break;
		case 545: question = "reisen"; correctAnswer = "travel"; break;
		case 546: question = "Baum"; correctAnswer = "tree"; break;
		case 547: question = "Dreieck"; correctAnswer = "triangle"; break;
		case 548: question = "Schwierigkeiten, Ärger"; correctAnswer = "trouble"; break;
		case 549: question = "Hose"; correctAnswer = "trousers"; break;
		case 550: question = "richtig, wahr"; correctAnswer = "true"; break;
		case 551: question = "probieren, versuchen"; correctAnswer = "try"; break;
		case 552: question = "U-Bahn"; correctAnswer = "tube"; break;
		case 553: question = "typisch"; correctAnswer = "typical"; break;
		case 554: question = "Onkel"; correctAnswer = "uncle"; break;
		case 555: question = "unter"; correctAnswer = "under"; break;
		case 556: question = "verstehen, begreifen"; correctAnswer = "understand"; break;
		case 557: question = "unglücklich, unzufrieden"; correctAnswer = "unhappy"; break;
		case 558: question = "Lektion"; correctAnswer = "unit"; break;
		case 559: question = "bis"; correctAnswer = "until"; break;
		case 560: question = "ungewöhnlich"; correctAnswer = "unsual || unusually"; break;
		case 561: question = "obem, nach oben"; correctAnswer = "up"; break;
		case 562: question = "verwenden"; correctAnswer = "use"; break;
		case 563: question = "gewöhnlich"; correctAnswer = "usual || usually"; break;
		case 564: question = "Gemüse"; correctAnswer = "vegetable"; break;
		case 565: question = "sehr"; correctAnswer = "very"; break;
		case 566: question = "Besuch, besuchen"; correctAnswer = "visit"; break;
		case 567: question = "warten"; correctAnswer = "wait"; break;
		case 568: question = "Kellner"; correctAnswer = "waiter"; break;
		case 569: question = "Kellnerin"; correctAnswer = "waitress"; break;
		case 570: question = "Spaziergang, zu Fuß gehen"; correctAnswer = "walk"; break;
		case 571: question = "Wand, Mauer"; correctAnswer = "wall"; break;
		case 572: question = "wollen"; correctAnswer = "want"; break;
		case 573: question = "warm"; correctAnswer = "warm"; break;
		case 574: question = "waschen"; correctAnswer = "wash"; break;
		case 575: question = "Armbanduhr"; correctAnswer = "watch"; break;
		case 576: question = "zusehen, beobachten"; correctAnswer = "watch"; break;
		case 577: question = "Wasser"; correctAnswer = "water"; break;
		case 578: question = "Weg, Art und Weise"; correctAnswer = "way"; break;
		case 579: question = "tragen"; correctAnswer = "wear || carry"; break;
		case 580: question = "Wetter"; correctAnswer = "weather"; break;
		case 581: question = "Woche"; correctAnswer = "week"; break;
		case 582: question = "Wochenende"; correctAnswer = "weekend"; break;
		case 583: question = "willkommen heißen"; correctAnswer = "welcome"; break;
		case 584: question = "gesund"; correctAnswer = "well"; break;
		case 585: question = "Westen"; correctAnswer = "west"; break;
		case 586: question = "was"; correctAnswer = "what"; break;
		case 587: question = "Rad"; correctAnswer = "wheel"; break;
		case 588: question = "wenn, als, wann"; correctAnswer = "when"; break;
		case 589: question = "wo, wohin"; correctAnswer = "where"; break;
		case 590: question = "welche, welcher, welches"; correctAnswer = "shich"; break;
		case 591: question = "weiß"; correctAnswer = "white"; break;
		case 592: question = "wer, der, die"; correctAnswer = "who"; break;
		case 593: question = "wen, wem"; correctAnswer = "whom"; break;
		case 594: question = "warum"; correctAnswer = "why"; break;
		case 595: question = "Ehefrau"; correctAnswer = "wife"; break;
		case 596: question = "werden"; correctAnswer = "become"; break;
		case 597: question = "gewinnen, siegen"; correctAnswer = "win"; break;
		case 598: question = "Fenster"; correctAnswer = "window"; break;
		case 599: question = "Wein"; correctAnswer = "wine"; break;
		case 600: question = "Winter"; correctAnswer = "winter"; break;
		case 601: question = "mit"; correctAnswer = "with"; break;
		case 602: question = "ohne"; correctAnswer = "without"; break;
		case 603: question = "Frau"; correctAnswer = "woman"; break;
		case 604: question = "wunderbar, wundervoll"; correctAnswer = "wonderfull"; break;
		case 605: question = "Wort"; correctAnswer = "word"; break;
		case 606: question = "Arbeit, arbeiten, funktionieren"; correctAnswer = "work"; break;
		case 607: question = "Welt"; correctAnswer = "world"; break;
		case 608: question = "schreiben"; correctAnswer = "write"; break;
		case 609: question = "falsch"; correctAnswer = "wrong"; break;
		case 610: question = "Jahr"; correctAnswer = "year"; break;
		case 611: question = "gelb"; correctAnswer = "yellow"; break;
		case 612: question = "gestern"; correctAnswer = "yesterday"; break;
		case 613: question = "jung"; correctAnswer = "young"; break;
		case 614: question = "Zoo"; correctAnswer = "zoo"; break;
		}
	}
	
	/*void recognizeUserIntent(String userRequest) {
			userRequest = userRequest.toLowerCase();
			String pattern75 = "\\balot\\b";
			
	
	Pattern p75 = Pattern.compile(pattern75);
	Matcher m75 = p75.matcher(userRequest);


	Object ourUserIntent;
	if (m75.find()) {
				ourUserIntent = UserIntent.alot;
			} else if (m76.find()) {
				ourUserIntent = UserIntent.about;
			} else {
						ourUserIntent = UserIntent.Error;
			}
			logger.info("set ourUserIntent to " +ourUserIntent);
		}*/
}